services:
  sql:
    image: mcr.microsoft.com/azure-sql-edge
    environment: 
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password@! 
    ports:
       - "1450:1433" 
    volumes:
      - sql-data:/var/opt/mssql